-- ============================================================
-- Afterdark.jo ticketing platform — initial schema
-- Mirrors prisma/schema.prisma 1:1. Generated by hand because
-- this sandbox cannot reach binaries.prisma.sh to run
-- `prisma migrate`. In a normal environment with full internet
-- access, `npx prisma migrate dev` against this same schema.prisma
-- would produce an equivalent migration.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE user_role AS ENUM ('ADMIN', 'STAFF', 'CUSTOMER');
CREATE TYPE order_status AS ENUM ('AWAITING_PAYMENT', 'PAYMENT_VERIFICATION', 'PAID', 'PAYMENT_REJECTED', 'CANCELLED', 'EXPIRED');
CREATE TYPE payment_status AS ENUM ('PENDING', 'AWAITING_ADMIN_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', 'REFUNDED');
CREATE TYPE ticket_status AS ENUM ('VALID', 'USED', 'CANCELLED', 'REFUNDED');
CREATE TYPE payment_method AS ENUM ('CLIQ');

CREATE TABLE users (
  id             TEXT PRIMARY KEY DEFAULT ('usr_' || replace(gen_random_uuid()::text, '-', '')),
  email          TEXT UNIQUE NOT NULL,
  password_hash  TEXT NOT NULL,
  full_name      TEXT NOT NULL,
  phone          TEXT,
  role           user_role NOT NULL DEFAULT 'CUSTOMER',
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE password_reset_tokens (
  id         TEXT PRIMARY KEY DEFAULT ('prt_' || replace(gen_random_uuid()::text, '-', '')),
  token      TEXT UNIQUE NOT NULL,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE categories (
  id         TEXT PRIMARY KEY DEFAULT ('cat_' || replace(gen_random_uuid()::text, '-', '')),
  name       TEXT UNIQUE NOT NULL,
  slug       TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE venues (
  id         TEXT PRIMARY KEY DEFAULT ('ven_' || replace(gen_random_uuid()::text, '-', '')),
  name       TEXT NOT NULL,
  address    TEXT NOT NULL,
  city       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE events (
  id              TEXT PRIMARY KEY DEFAULT ('evt_' || replace(gen_random_uuid()::text, '-', '')),
  slug            TEXT UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  description     TEXT NOT NULL,
  rules           TEXT,
  age_restriction TEXT,
  dress_code      TEXT,
  cover_image_url TEXT,
  category_id     TEXT NOT NULL REFERENCES categories(id),
  venue_id        TEXT NOT NULL REFERENCES venues(id),
  start_date      TIMESTAMPTZ NOT NULL,
  end_date        TIMESTAMPTZ NOT NULL,
  is_published    BOOLEAN NOT NULL DEFAULT FALSE,
  seo_title       TEXT,
  seo_description TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_events_published_start ON events(is_published, start_date);

CREATE TABLE ticket_types (
  id               TEXT PRIMARY KEY DEFAULT ('tty_' || replace(gen_random_uuid()::text, '-', '')),
  event_id         TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name             TEXT NOT NULL,
  description      TEXT,
  price            NUMERIC(10,2) NOT NULL,
  currency         TEXT NOT NULL DEFAULT 'JOD',
  total_inventory  INTEGER NOT NULL,
  reserved_count   INTEGER NOT NULL DEFAULT 0,
  sold_count       INTEGER NOT NULL DEFAULT 0,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order       INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_inventory_nonneg CHECK (reserved_count >= 0 AND sold_count >= 0),
  CONSTRAINT chk_inventory_capacity CHECK (reserved_count + sold_count <= total_inventory)
);
CREATE INDEX idx_ticket_types_event ON ticket_types(event_id);

-- Server-side atomic sequence for human-readable ticket numbers.
CREATE TABLE ticket_number_sequence (
  id          INTEGER PRIMARY KEY DEFAULT 1,
  last_number INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT single_row CHECK (id = 1)
);
INSERT INTO ticket_number_sequence (id, last_number) VALUES (1, 0);

CREATE TABLE orders (
  id                     TEXT PRIMARY KEY DEFAULT ('ord_' || replace(gen_random_uuid()::text, '-', '')),
  order_number           TEXT UNIQUE NOT NULL,
  customer_id            TEXT REFERENCES users(id),
  customer_full_name     TEXT NOT NULL,
  email                  TEXT NOT NULL,
  phone                  TEXT NOT NULL,
  event_id               TEXT NOT NULL REFERENCES events(id),
  total_amount           NUMERIC(10,2) NOT NULL,
  currency               TEXT NOT NULL DEFAULT 'JOD',
  status                 order_status NOT NULL DEFAULT 'AWAITING_PAYMENT',
  reservation_expires_at TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_email ON orders(email);

CREATE TABLE order_items (
  id             TEXT PRIMARY KEY DEFAULT ('oit_' || replace(gen_random_uuid()::text, '-', '')),
  order_id       TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  ticket_type_id TEXT NOT NULL REFERENCES ticket_types(id),
  quantity       INTEGER NOT NULL,
  unit_price     NUMERIC(10,2) NOT NULL,
  subtotal       NUMERIC(10,2) NOT NULL
);

CREATE TABLE payments (
  id               TEXT PRIMARY KEY DEFAULT ('pay_' || replace(gen_random_uuid()::text, '-', '')),
  order_id         TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  method           payment_method NOT NULL DEFAULT 'CLIQ',
  amount           NUMERIC(10,2) NOT NULL,
  currency         TEXT NOT NULL DEFAULT 'JOD',
  status           payment_status NOT NULL DEFAULT 'PENDING',
  submitted_at     TIMESTAMPTZ,
  verified_at      TIMESTAMPTZ,
  verified_by_id   TEXT REFERENCES users(id),
  rejection_reason TEXT,
  admin_note       TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_status ON payments(status);

CREATE TABLE tickets (
  id               TEXT PRIMARY KEY DEFAULT ('tkt_' || replace(gen_random_uuid()::text, '-', '')),
  ticket_number    TEXT UNIQUE NOT NULL,
  qr_token         TEXT UNIQUE NOT NULL,
  order_id         TEXT NOT NULL REFERENCES orders(id),
  customer_name    TEXT NOT NULL,
  event_id         TEXT NOT NULL REFERENCES events(id),
  ticket_type_id   TEXT NOT NULL REFERENCES ticket_types(id),
  status           ticket_status NOT NULL DEFAULT 'VALID',
  pdf_path         TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  used_at          TIMESTAMPTZ,
  checked_in_by_id TEXT
);
CREATE INDEX idx_tickets_qr_token ON tickets(qr_token);
CREATE INDEX idx_tickets_number ON tickets(ticket_number);

CREATE TABLE check_ins (
  id         TEXT PRIMARY KEY DEFAULT ('chk_' || replace(gen_random_uuid()::text, '-', '')),
  ticket_id  TEXT NOT NULL REFERENCES tickets(id),
  staff_id   TEXT REFERENCES users(id),
  result     TEXT NOT NULL, -- VALID_CHECKED_IN | ALREADY_USED | INVALID
  location   TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
  id              TEXT PRIMARY KEY DEFAULT ('log_' || replace(gen_random_uuid()::text, '-', '')),
  admin_id        TEXT REFERENCES users(id),
  order_id        TEXT REFERENCES orders(id),
  action          TEXT NOT NULL,
  previous_status TEXT,
  new_status      TEXT,
  reason          TEXT,
  metadata        JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_logs_order ON audit_logs(order_id);

CREATE TABLE site_settings (
  id                    INTEGER PRIMARY KEY DEFAULT 1,
  business_name         TEXT NOT NULL DEFAULT 'Afterdark.jo',
  cliq_alias            TEXT NOT NULL DEFAULT 'SET_ME_IN_ADMIN',
  payment_instructions  TEXT NOT NULL DEFAULT 'Transfer the exact amount via CliQ to the alias above, then confirm below.',
  support_phone         TEXT NOT NULL DEFAULT '+962 7 0000 0000',
  support_email         TEXT NOT NULL DEFAULT 'support@example.com',
  reservation_minutes   INTEGER NOT NULL DEFAULT 15,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT single_settings_row CHECK (id = 1)
);
INSERT INTO site_settings (id) VALUES (1);
